name: Automating PRs Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ec2-user
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2.key
          chmod 600 ~/.ssh/ec2.key
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Deploy or Update Container
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          scp -i ~/.ssh/ec2.key -r ./* ${EC2_USERNAME}@${EC2_HOST}:~/pr-${PR_NUMBER}
          ssh -i ~/.ssh/ec2.key ${EC2_USERNAME}@${EC2_HOST} << EOF
            cd ~/pr-${PR_NUMBER}
            echo "PR_NUMBER=${PR_NUMBER}" > .env
            echo "GITHUB_SHA=${GITHUB_SHA}" >> .env
            
            # Check if the container already exists
            if docker ps -a --format '{{.Names}}' | grep -q "^pr-${PR_NUMBER}$"; then
              echo "Updating existing container"
              docker-compose down
              docker-compose build --no-cache
              docker-compose up -d
            else
              echo "Creating new container"
              docker-compose up -d --build
            fi
            
            # Prune old images to save space
            docker image prune -af
          EOF
        continue-on-error: true
        id: deploy

      - name: Check Deployment Status
        if: steps.deploy.outcome == 'failure'
        run: |
          echo "Deployment failed. Check the logs for more information."
          exit 1

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = '${{ github.event.pull_request.number }}';
            const deploymentUrl = `http://${process.env.EC2_HOST}:${prNumber}`;
            const body = `Deployment for PR #${prNumber} is live!\nURL: ${deploymentUrl}\nCommit: ${{ github.sha }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

  cleanup:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2.key
          chmod 600 ~/.ssh/ec2.key
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Cleanup Container and Resources
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          ssh -i ~/.ssh/ec2.key ${EC2_USERNAME}@${EC2_HOST} << EOF
            cd ~/pr-${PR_NUMBER}
            docker-compose down -v --rmi all
            cd ~
            rm -rf pr-${PR_NUMBER}
            
            # Remove any dangling images and volumes
            docker system prune -af --volumes
          EOF

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = '${{ github.event.pull_request.number }}';
            const body = `PR #${prNumber} environment has been cleaned up. All associated containers, images, and volumes have been removed.`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
